### ISSUE TITLE
Controller 'ngInclude', required by directive 'formForIncludeReplace', can't be found!

### ISSUE THREAD

**Issue by mydearxym** [bvaughn/angular-form-for#107]
thanks for the work!
i just follow the readme on website , but i got lots of error on the console : 
```javascript 
Error: [$compile:ctreq] Controller 'ngInclude', required by directive 'formForIncludeReplace', can't be found!
http://errors.angularjs.org/1.2.3/$compile/ctreq?p0=ngInclude&p1=formForIncludeReplace
    at http://localhost:9000/bower_components/angular/angular.js:78:12
    at getControllers (http://localhost:9000/bower_components/angular/angular.js:5967:19)
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:6134:35)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:5545:15)
    at publicLinkFn (http://localhost:9000/bower_components/angular/angular.js:5453:30)
    at boundTranscludeFn (http://localhost:9000/bower_components/angular/angular.js:5564:21)
    at controllersBoundTransclude (http://localhost:9000/bower_components/angular/angular.js:6154:18)
    at http://localhost:9000/bower_components/angular/angular.js:18287:27
    at http://localhost:9000/bower_components/angular/angular.js:7474:11
    at deferred.promise.then.wrappedCallback (http://localhost:9000/bower_components/angular/angular.js:10689:81) <span ng-if="!enableFiltering &amp;&amp; !multiple" ng-include="" form-for-include-replace="" src="'form-for/templates/select-field/_select.html'" class="ng-scope">(anonymous function) @ angular.js:9193$get @ angular.js:6746nodeLinkFn @ angular.js:6136compositeLinkFn @ angular.js:5545publicLinkFn @ angular.js:5453boundTranscludeFn @ angular.js:5564controllersBoundTransclude @ angular.js:6154(anonymous function) @ angular.js:18287(anonymous function) @ angular.js:7474deferred.promise.then.wrappedCallback @ angular.js:10689deferred.promise.then.wrappedCallback @ angular.js:10689(anonymous function) @ angular.js:10775$get.Scope.$eval @ angular.js:11668$get.Scope.$digest @ angular.js:11513$get.Scope.$apply @ angular.js:11774(anonymous function) @ angular.js:1297invoke @ angular.js:3638doBootstrap @ angular.js:1295bootstrap @ angular.js:1309angularInit @ angular.js:1258(anonymous function) @ angular.js:20277jQuery.Callbacks.fire @ jquery.js:3073jQuery.Callbacks.self.fireWith @ jquery.js:3185jQuery.extend.ready @ jquery.js:3391completed @ jquery.js:3407
angular.js:9193 Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [["fn: parentValueWatch; newVal: [{\"value\":\"female\",\"label\":\"Female\"},{\"value\":\"male\",\"label\":\"Male\"}]; oldVal: [{\"value\":\"female\",\"label\":\"Female\"},{\"value\":\"male\",\"label\":\"Male\"}]","fn: $watchCollectionWatch; newVal: 16; oldVal: 14","fn: parentValueWatch; newVal: [{\"label\":\"Search engine\",\"value\":1},{\"label\":\"Forum\",\"value\":2},{\"label\":\"Friend\",\"value\":3},{\"label\":\"Other\",\"value\":4}]; oldVal: [{\"label\":\"Search engine\",\"value\":1},{\"label\":\"Forum\",\"value\":2},{\"label\":\"Friend\",\"value\":3},{\"label\":\"Other\",\"value\":4}]"],["fn: parentValueWatch; newVal: [{\"value\":\"female\",\"label\":\"Female\"},{\"value\":\"male\",\"label\":\"Male\"}]; oldVal: [{\"value\":\"female\",\"label\":\"Female\"},{\"value\":\"male\",\"label\":\"Male\"}]","fn: $watchCollectionWatch; newVal: 18; oldVal: 16","fn: parentValueWatch; newVal: [{\"label\":\"Search engine\",\"value\":1},{\"label\":\"Forum\",\"value\":2},{\"label\":\"Friend\",\"value\":3},{\"label\":\"Other\",\"value\":4}]; oldVal: [{\"label\":\"Search engine\",\"value\":1},{\"label\":\"Forum\",\"value\":2},{\"label\":\"Friend\",\"value\":3},{\"label\":\"Other\",\"value\":4}]"],["fn: parentValueWatch; newVal: [{\"value\":\"female\",\"label\":\"Female\"},{\"value\":\"male\",\"label\":\"Male\"}]; oldVal: [{\"value\":\"female\",\"label\":\"Female\"},{\"value\":\"male\",\"label\":\"Male\"}]","fn: $watchCollectionWatch; newVal: 20; oldVal: 18","fn: parentValueWatch; newVal: [{\"label\":\"Search engine\",\"value\":1},{\"label\":\"Forum\",\"value\":2},{\"label\":\"Friend\",\"value\":3},{\"label\":\"Other\",\"value\":4}]; oldVal: [{\"label\":\"Search engine\",\"value\":1},{\"label\":\"Forum\",\"value\":2},{\"label\":\"Friend\",\"value\":3},{\"label\":\"Other\",\"value\":4}]"],["fn: parentValueWatch; newVal: [{\"value\":\"female\",\"label\":\"Female\"},{\"value\":\"male\",\"label\":\"Male\"}]; oldVal: [{\"value\":\"female\",\"label\":\"Female\"},{\"value\":\"male\",\"label\":\"Male\"}]","fn: $watchCollectionWatch; newVal: 22; oldVal: 20","fn: parentValueWatch; newVal: [{\"label\":\"Search engine\",\"value\":1},{\"label\":\"Forum\",\"value\":2},{\"label\":\"Friend\",\"value\":3},{\"label\":\"Other\",\"value\":4}]; oldVal: [{\"label\":\"Search engine\",\"value\":1},{\"label\":\"Forum\",\"value\":2},{\"label\":\"Friend\",\"value\":3},{\"label\":\"Other\",\"value\":4}]"],["fn: parentValueWatch; newVal: [{\"value\":\"female\",\"label\":\"Female\"},{\"value\":\"male\",\"label\":\"Male\"}]; oldVal: [{\"value\":\"female\",\"label\":\"Female\"},{\"value\":\"male\",\"label\":\"Male\"}]","fn: $watchCollectionWatch; newVal: 24; oldVal: 22","fn: parentValueWatch; newVal: [{\"label\":\"Search engine\",\"value\":1},{\"label\":\"Forum\",\"value\":2},{\"label\":\"Friend\",\"value\":3},{\"label\":\"Other\",\"value\":4}]; oldVal: [{\"label\":\"Search engine\",\"value\":1},{\"label\":\"Forum\",\"value\":2},{\"label\":\"Friend\",\"value\":3},{\"label\":\"Other\",\"value\":4}]"]]

```

**Comment by bvaughn** [comment]
Hmm. I'm sorry to hear it. Any chance you could point me at a Plunker with this problem? I'd be happy to take a look but my schedule's pretty busy at the moment.

**Comment by mydearxym** [comment]
thanks ~  i think this may be the version issue 
i change back to 1.7.2 and angular 1.2.x and it works well ~
